[profile.release]
# lto = true
# codegen-units = 1
opt-level = 3
rustflags = ["-C","target-cpu=native"]

[build]
# # target = "x86_64-unknown-linux-gnu"
rustflags = ["-C","target-cpu=native"]
# rustflags = ["--cfg",'debug="normal_rendering"']