[profile.release]
opt-level = 3
lto = true
debug = true
# codegen-units = 1


[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ["-C","target-cpu=native"]
# rustflags = ["--cfg",'debug="normal_rendering"']